### ISSUE TITLE
How to use the defense framework you presented in your paper？

### ISSUE THREAD

**Issue by jamesliu609** [qiufan319/benchmark_pc_attack#1]
Hi, thanks a lot for this work! Where is your defense method and how should I use it? Could you please provide detailed instructions. Also in AT I have a point of confusion, in line 263 the code reads: `train_set=torch.utils.data.ConcatDataset([orig_trainset,orig_trainset])`.
Shouldn't it be org_trainset and adv_trainset that are used for adversarial training, why are two identical org_trainset connected here. Thank you very much if you can answer my confusion!

**Comment by qiufan319** [comment]
> Hi, thanks a lot for this work! Where is your defense method and how should I use it? Could you please provide detailed instructions. Also in AT I have a point of confusion, in line 263 the code reads: `train_set=torch.utils.data.ConcatDataset([orig_trainset,orig_trainset])`. Shouldn't it be org_trainset and adv_trainset that are used for adversarial training, why are two identical org_trainset connected here. Thank you very much if you can answer my confusion!

Hi @jamesliu609 , thank you for your correction. The correct code on AT should be: `train_set=torch.utils.data.ConcatDataset([orig_trainset,adv_trainset])`. And I have updated the hybrid training and instruction in the latest version.  If you have any further questions, please feel free to ask me.
